version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: classroom_online
      POSTGRES_TZ: Asia/Bangkok  # เพิ่ม timezone ที่นี่
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always  # เพิ่มเพื่อให้ container รีสตาร์ทอัตโนมัติในกรณีที่หยุดทำงาน

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always  # เพิ่มเพื่อให้ container รีสตาร์ทอัตโนมัติในกรณีที่หยุดทำงาน

volumes:
  postgres-data:
